# This File Is Generated By CreatelientGui.py
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 60)

        self.frame_x = QtWidgets.QFrame(Dialog)
        self.frame_x.setGeometry(QtCore.QRect(0, 0, 350, 60))
        self.frame_x.setStyleSheet("font:10pt \"Segoe UI\";\nbackground-color: rgb(30, 100, 100);")
        self.frame_x.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_x.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_x.setObjectName("frame_x")
        self.label_name_2 = QtWidgets.QLabel(self.frame_x)
        self.label_name_2.setGeometry(QtCore.QRect(10, 0, 331, 41))
        self.label_name_2.setObjectName("label_name_2")
        self.label_num_2 = QtWidgets.QLabel(self.frame_x)
        self.label_num_2.setGeometry(QtCore.QRect(10, 30, 321, 21))
        self.label_num_2.setObjectName("label_num_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate

        Dialog.setWindowTitle(_translate("Dialog", "Connected Clients"))

        self.label_name_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Hotspot Name: Porcupine Tree"
                                                       "</span></p></body></html>"))
        self.label_num_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:"
                                                      "#ffffff;\">Clients Connected: 0</span></p></body></html>"))

